// ... other import statements ...
import events from "./events";
import eventFees from "./admin/events/fees";
// ... other import statements ...

// ... other code ...

// Admin routes
router.use("/api/admin/events", requireAdmin, events);
router.use("/api/admin/events/:eventId/fees", eventFees);

// ... rest of the router configuration ...